 export enum ProcessorErrorEnums {
     PROCESSOR_INSTAGRAM_INVALID_FILE_CODE = 'CON-PRO-001',
     PROCESSOR_FACEBOOK_INVALID_FILE_CODE = 'CON-PRO-002',
     PROCESSOR_AMAZON_INVALID_FILE_CODE = 'CON-PRO-003',
 }
