
export enum DescriptorErrorEnum {
    ALL_SOURCES_CODES_ERROR = 'CON-DES-001',
    SOURCE_NAME_ERROR = 'CON-DES-002',
    SOURCE_FORMAT_ERROR = 'CON-DES-003',
    SOURCE_PROCEDURE_ERROR = 'CON-DES-004',
    SOURCE_ALL_PROCEDURES_ERROR = 'CON-DES-005',
    SOURCE_ALL_LANGUAGES_ERROR = 'CON-DES-006',
    SOURCE_DESCRIPTION_ERROR = 'CON-DES-007',
}