export enum DataSourceCode {
    INSTAGRAM = 'INSTAGRAM',
    FACEBOOK = 'FACEBOOK',
    GOOGLE = 'GOOGLE',
    NETFLIX = 'NETFLIX',
    AMAZON = 'AMAZON',
    LINKEDIN = 'LINKEDIN'
}

export enum RetrievingProcedureType {
    DEFAULT = 'DEFAULT',
    DESKTOP = 'DESKTOP',
    MOBILE = 'MOBILE'
}

export enum FileCode {
    INSTAGRAM_ADS_CLICKED,
    INSTAGRAM_ADS_VIEWED,
    INSTAGRAM_POST_COMMENT,
    INSTAGRAM_EMOJI_SLIDERS,
    INSTAGRAM_FOLLOWERS,
    INSTAGRAM_FOLLOWING,
    INSTAGRAM_LIKE_COMMENTS,
    INSTAGRAM_LIKE_POSTS,
    INSTAGRAM_ELEGIBILITY,
    INSTAGRAM_POLL,
    INSTAGRAM_POSTS_CREATED,
    INSTAGRAM_POSTS_VIEWED,
    INSTAGRAM_QUIZZES,
    INSTAGRAM_STORIES_CREATED,
    INSTAGRAM_VIDEO_CREATED
}