export enum FileCodeLinkedIn {
    JOBS_APPLICATIONS = 'Jobs/Job Applications.csv',
    JOBS_SEEKER_PREFERENCES = 'Jobs/Job Seeker Preferences.csv',
    JOBS_SAVED_JOBS = 'Jobs/Saved Jobs.csv',
    ACCOUNT_STATUS_HISTORY = 'Account Status History.csv',
    ADS_CLICKED = 'Ads Clicked.csv',
    ADS_TARGETING = 'Ad_Targeting.csv',
    COMPANY_FOLLOWS = 'Company Follows.csv',
    CONNECTIONS = 'Connections.csv',
    CONTACTS = 'Contacts.csv',
    EDUCATION = 'Education.csv',
    EMAIL_ADDRESSES = 'Email Addresses.csv',
    ENDORSEMENT_RECEIVED_INFO_2 = 'Endorsement_Received_Info.csv',
    INFERENCES_ABOUT_YOU = 'Inferences_about_you.csv',
    INVITATIONS = 'Invitations.csv',
    JOB_APPLICANT_SAVED_ANSWERS = 'Job Applicant Saved Answers.csv',
    JOB_APPLICANT_SAVED_QUESTION_RESPONSES = 'Job Applicant Saved Screening Question Responses.csv',
    LEARNING = 'Learning.csv',
    LOGINS = 'Logins.csv',
    MEMBER_FOLLOWS = 'Member_Follows.csv',
    MESSAGE = 'messages.csv',
    PHONE_NUMBERS = 'PhoneNumbers.csv',
    POSITIONS = 'Positions.csv',
    PROFILE = 'Profile.csv',
    REACTIONS = 'Reactions.csv',
    REGISTRATION = 'Registration.csv',
    RICH_MEDIA = 'Rich Media.csv',
    SAVED_JOBS_ALERTS = 'SavedJobAlerts.csv',
    SEARCH_QUERIES = 'SearchQueries.csv',
    SECURITY_CHALLENGES = 'Security Challenges.csv',
    SKILLS = 'Skills.csv',
    VOTES = 'Votes.csv',
    //TODO: not parsed yet
    ENDORSEMENT_RECEIVED_INFO_1 = 'Endorsement Received Info.csv',
}
