export enum ValidationErrorEnums {
    LANGUAGE_ERROR = 'CON-VAL-001',
    MISSING_FILE_ERROR = 'CON-VAL-002',
    FILE_EXTENSION_ERROR = 'CON-VAL-003',
    ZIPPING_FILE_ERROR = 'CON-VAL-004',
    NOT_VALID_FILES_ERROR = 'CON-VAL-009',
    NO_USEFUL_FILES_ERROR = 'CON-VAL-010',
}
