export enum ValidationErrorEnums {
    LANGUAGE_ERROR = 'CON-VAL-001',
    MISSING_FILE_ERROR = 'CON-VAL-002',
    FILE_EXTENSION_ERROR = 'CON-VAL-003',
    JSON_ERROR = 'CON-VAL-004',
    CSV_ERROR = 'CON-VAL-005',
    XML_ERROR = 'CON-VAL-006',
    HTML_ERROR = 'CON-VAL-007',
    TXT_ERROR = 'CON-VAL-008',
}